# Description

Generates manubot tables for PhenomeXcan and eMERGE associations given an LV name (which is the only parameter that needs to be specified in the Settings section below).

# Modules loading

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import re
from pathlib import Path

import pandas as pd

from entity import Trait
import conf

# Settings

In [3]:
LV_NAME = "LV24"

In [4]:
# assert (
#     conf.MANUSCRIPT["BASE_DIR"] is not None
# ), "The manuscript directory was not configured"

# OUTPUT_FILE_PATH = conf.MANUSCRIPT["CONTENT_DIR"] / "50.00.supplementary_material.md"
# display(OUTPUT_FILE_PATH)
# assert OUTPUT_FILE_PATH.exists()

In [5]:
# result_set is either phenomexcan or emerge
# LV_FILE_MARK_TEMPLATE = "<!-- {lv}:{result_set}_traits_assocs:{position} -->"

In [6]:
# TABLE_CAPTION = "Table: Significant trait associations of {lv_name} in {result_set_name}. {table_id}"

In [7]:
# TABLE_CAPTION_ID = "#tbl:sup:{result_set}_assocs:{lv_name_lower_case}"

In [8]:
RESULT_SET_NAMES = {
    "phenomexcan": "PhenomeXcan",
    "emerge": "eMERGE",
}

# Load data

## PhenomeXcan LV-trait associations

In [9]:
input_filepath = Path(conf.RESULTS["GLS"] / "gls-summary-phenomexcan.pkl.gz")
display(input_filepath)

PosixPath('/opt/data/results/gls/gls-summary-phenomexcan.pkl.gz')

In [11]:
phenomexcan_lv_trait_assocs = pd.read_pickle(input_filepath)

In [12]:
phenomexcan_lv_trait_assocs.shape

(4037817, 5)

In [13]:
phenomexcan_lv_trait_assocs.head()

         phenotype        phenotype_desc     lv    pvalue       fdr
0  AB1_OTHER_VIRAL  Other viral diseases  LV736  0.004725  0.504339
1  AB1_OTHER_VIRAL  Other viral diseases  LV320  0.004848  0.508291
2  AB1_OTHER_VIRAL  Other viral diseases  LV366  0.005306  0.523691
3  AB1_OTHER_VIRAL  Other viral diseases  LV964  0.006106  0.548143
4  AB1_OTHER_VIRAL  Other viral diseases   LV92  0.006565  0.560048

In [64]:
with pd.option_context(
    "display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None
):
    _tmp = phenomexcan_lv_trait_assocs[
        (phenomexcan_lv_trait_assocs["lv"] == "LV24")
        & (phenomexcan_lv_trait_assocs["pvalue"] < 0.01)
    ].sort_values("pvalue")
    
    display(_tmp)

,phenotype,phenotype_desc,lv,pvalue,fdr
1367986,4101_raw,Heel broadband ultrasound attenuation (left),LV24,1.850282e-21,1.464922e-16
1064977,4120_raw,Heel broadband ultrasound attenuation (right),LV24,2.169228e-21,1.684413e-16
2039146,4124_raw,Heel bone mineral density (BMD) (right),LV24,4.254136e-12,4.580646e-08
463894,4123_raw,"Heel quantitative ultrasound index (QUI), direct entry (right)",LV24,5.295114e-12,5.557142e-08
3587749,4125_raw,"Heel bone mineral density (BMD) T-score, automated (right)",LV24,5.298654e-12,5.557142e-08
4018083,MAGNETIC_CH2.DB.ratio,CH2DB NMR,LV24,8.883343e-11,7.441766e-07
790591,4105_raw,Heel bone mineral density (BMD) (left),LV24,9.692989e-11,8.036656e-07
118444,4104_raw,"Heel quantitative ultrasound index (QUI), direct entry (left)",LV24,1.357855e-10,1.082856e-06
2049016,4106_raw,"Heel bone mineral density (BMD) T-score, automated (left)",LV24,1.359666e-10,1.082856e-06
1587100,3148_raw,Heel bone mineral density (BMD),LV24,1.296695e-09,8.245383e-06
678075,2463,Fractured/broken bones in last 5 years,LV24,1.430898e-09,8.999539e-06
3941096,3147_raw,"Heel quantitative ultrasound index (QUI), direct entry",LV24,1.742800e-09,1.075086e-05
918902,78_raw,"Heel bone mineral density (BMD) T-score, automated",LV24,1.743966e-09,1.075086e-05
1621646,3144_raw,"Heel Broadband ultrasound attenuation, direct entry",LV24,4.776883e-09,2.634997e-05
3556166,S52,Diagnoses - main ICD10: S52 Fracture of forearm,LV24,6.229938e-07,1.754208e-03
2494153,6151_5,Fractured bone site(s): Wrist,LV24,7.690623e-07,2.082718e-03
4033875,GEFOS_Forearm,Bone Mineral Density,LV24,1.300576e-06,3.204080e-03
936663,20003_1140882910,Treatment/medication code: daktacort cream (20003_1140882910),LV24,3.102543e-06,6.391582e-03
3165311,I9_VASCINT,Vascular diseases of the intestine,LV24,3.649257e-04,1.724447e-01
1849638,20079_3,Day-of-week questionnaire completion requested: Wednesday,LV24,4.227335e-04,1.867051e-01
3599596,20086_8,Type of special diet followed: Gluten-free,LV24,8.406194e-04,2.623398e-01
636617,3446_2,Type of tobacco currently smoked: Hand-rolled cigarettes,LV24,9.077753e-04,2.721383e-01
3358769,N81,Diagnoses - main ICD10: N81 Female genital prolapse,LV24,1.082125e-03,2.938970e-01
73047,20002_1309,"Non-cancer illness code, self-reported: osteoporosis",LV24,1.556714e-03,3.408561e-01
774801,22617_2317,Job SOC coding: Registrars and senior administrators of educational establishments,LV24,1.706436e-03,3.521208e-01
3163342,22617_8133,Job SOC coding: Routine inspectors and testers,LV24,1.917909e-03,3.681795e-01
3041941,22601_12333358,Job coding: hairdressing or beauty salon manager or proprietor/owner (22601_12333358),LV24,2.132570e-03,3.827418e-01
2413222,22617_1233,Job SOC coding: Hairdressing and beauty salon managers and proprietors,LV24,2.230648e-03,3.899359e-01
263532,20003_1141200004,Treatment/medication code: pregabalin (20003_1141200004),LV24,2.601107e-03,4.134308e-01
1791410,ENDOMETRIOSIS_UTERUS,Endometriosis of uterus,LV24,2.614224e-03,4.139025e-01
659322,22650_9,Night shifts worked: This type of shift pattern was not worked during job,LV24,2.639761e-03,4.152106e-01
1324560,NECROVASC_FG,#Other necrotizing vasculopathies (FG),LV24,2.744955e-03,4.210937e-01
3009369,22601_41413308,"Job coding: telephonist, telephone/switchboard operator (22601_41413308)",LV24,2.772305e-03,4.223945e-01
1024516,6145_4,"Illness, injury, bereavement, stress in last 2 years: Death of a spouse or partner",LV24,2.873799e-03,4.279477e-01
2173380,20003_1141172492,Treatment/medication code: micardis 20mg tablet (20003_1141172492),LV24,3.010841e-03,4.352547e-01
1556500,20003_1141174508,Treatment/medication code: reductil 10mg capsule (20003_1141174508),LV24,3.075948e-03,4.384413e-01
2622461,20107_101,Illnesses of father: None of the above (group 2),LV24,3.227753e-03,4.451034e-01
3724941,20003_1140878186,Treatment/medication code: liquifilm tears 1.4% eye drops (20003_1140878186),LV24,3.365333e-03,4.513320e-01
3540377,3872_raw,Age of primiparous women at birth of child,LV24,3.474583e-03,4.560814e-01
2058884,G6_ULLNLE,Lesion of ulnar nerve,LV24,3.478843e-03,4.564100e-01
1356140,T17,Diagnoses - main ICD10: T17 Foreign body in respiratory tract,LV24,3.841305e-03,4.726637e-01
3125834,22601_54322893,"Job coding: baker, confectioner, pastry cook, cake decorator (22601_54322893)",LV24,3.936955e-03,4.766628e-01
950486,H7_RETINANAS,Other specified and unspecified retinal disorders,LV24,4.164909e-03,4.847688e-01
1840766,S64,Diagnoses - main ICD10: S64 Injury of nerves at wrist and hand level,LV24,4.196157e-03,4.858287e-01
3838452,20024_2211,Job code - deduced: Medical practitioners,LV24,4.344884e-03,4.911128e-01
835993,20003_1140910640,Treatment/medication code: luteine (20003_1140910640),LV24,4.822461e-03,5.074325e-01
1776612,20002_1234,"Non-cancer illness code, self-reported: adrenocortical insufficiency/addison's disease",LV24,4.849718e-03,5.082911e-01
2022372,RHEUMA_CHRYSTAL,"Chrystal arthropathies, rheuma endpoint",LV24,4.924928e-03,5.111488e-01
2183256,22601_23173422,"Job coding: registrar or senior administrator of educational establishment, bursar, registrar, university administrator (22601_23173422)",LV24,5.614943e-03,5.339058e-01
2477387,1448_4,Bread type: Other type of bread,LV24,5.873931e-03,5.414571e-01
2265173,20003_1140869930,Treatment/medication code: azathioprine (20003_1140869930),LV24,6.188523e-03,5.505460e-01
3848321,2926,Number of unsuccessful stop-smoking attempts,LV24,7.032390e-03,5.720708e-01
3405172,K11_OTHDIG,Other diseases of the digestive system,LV24,7.156003e-03,5.747887e-01
3237368,22601_41213240,Job coding: credit controller/supervisor (22601_41213240),LV24,7.297289e-03,5.784079e-01
1429194,Z42,Diagnoses - main ICD10: Z42 Follow-up care involving plastic surgery,LV24,7.561553e-03,5.840570e-01
2982726,22617_4141,Job SOC coding: Telephonists,LV24,8.147056e-03,5.970121e-01
2015467,20003_1140873474,Treatment/medication code: lymecycline (20003_1140873474),LV24,8.467443e-03,6.029980e-01
3614409,20445,Depression possibly related to childbirth,LV24,8.494602e-03,6.035058e-01
2861320,CHILDHOOD_ALLERGY,Childhood allergy (age < 16),LV24,8.800268e-03,6.098453e-01
1367021,20002_1225,"Non-cancer illness code, self-reported: hyperthyroidism/thyrotoxicosis",LV24,9.528098e-03,6.242343e-01
3085376,20002_1371,"Non-cancer illness code, self-reported: sarcoidosis",LV24,9.585211e-03,6.255575e-01
1209089,22617_8229,Job SOC coding: Mobile machine drivers and operatives n.e.c.,LV24,9.724746e-03,6.278339e-01
1918738,20003_1140873450,Treatment/medication code: tetracycline (20003_1140873450),LV24,9.772744e-03,6.288434e-01
664261,20404,Ever physically dependent on alcohol,LV24,9.787495e-03,6.291209e-01

## eMERGE LV-trait associations

In [14]:
input_filepath = Path(conf.RESULTS["GLS"] / "gls-summary-emerge.pkl.gz")
display(input_filepath)

PosixPath('/opt/data/results/gls/gls-summary-emerge.pkl.gz')

In [15]:
emerge_lv_trait_assocs = pd.read_pickle(input_filepath)

In [16]:
emerge_lv_trait_assocs.shape

(304983, 5)

In [17]:
emerge_lv_trait_assocs.head()

,phenotype,phenotype_desc,lv,pvalue,fdr
0,EUR_440.2,Atherosclerosis of the extremities,LV472,1.033637e-07,0.000658
1,EUR_440.2,Atherosclerosis of the extremities,LV182,3.710244e-07,0.001432
2,EUR_440.2,Atherosclerosis of the extremities,LV348,7.379936e-07,0.002558
3,EUR_440.2,Atherosclerosis of the extremities,LV504,1.534424e-06,0.004500
4,EUR_440.2,Atherosclerosis of the extremities,LV445,2.912525e-06,0.007402

In [65]:
with pd.option_context(
    "display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None
):
    _tmp = emerge_lv_trait_assocs[
        (emerge_lv_trait_assocs["lv"] == "LV24")
        & (emerge_lv_trait_assocs["pvalue"] < 0.01)
    ].sort_values("pvalue")
    
    display(_tmp)

,phenotype,phenotype_desc,lv,pvalue,fdr
53301,EUR_743.1,Osteoporosis,LV24,0.001955,0.392564
76990,EUR_365,Glaucoma,LV24,0.002250,0.411932
35536,EUR_687.1,Rash and other nonspecific skin eruption,LV24,0.003306,0.467492

## eMERGE traits info

In [18]:
input_filepath = conf.EMERGE["DESC_FILE_WITH_SAMPLE_SIZE"]
display(input_filepath)

PosixPath('/opt/data/data/emerge/eMERGE_III_PMBB_GSA_v2_2020_phecode_AFR_EUR_cc50_counts_w_dictionary.txt')

In [20]:
emerge_traits_info = pd.read_csv(
    input_filepath,
    sep="\t",
    dtype={"phecode": str},
    usecols=[
        "phecode",
        "phenotype",
        "category",
        "eMERGE_III_EUR_case",
        "eMERGE_III_EUR_control",
    ],
)

In [21]:
emerge_traits_info["phecode"] = emerge_traits_info["phecode"].apply(
    lambda x: f"EUR_{x}"
)

In [22]:
emerge_traits_info = emerge_traits_info.set_index("phecode").sort_index()

In [23]:
emerge_traits_info = emerge_traits_info.rename(
    columns={
        "eMERGE_III_EUR_case": "eur_n_cases",
        "eMERGE_III_EUR_control": "eur_n_controls",
    }
)

In [24]:
emerge_traits_info.shape

(309, 4)

In [25]:
emerge_traits_info.head()

,eur_n_cases,eur_n_controls,phenotype,category
phecode,,,,
EUR_008,1639,57495,Intestinal infection,infectious diseases
EUR_008.5,1024,57495,Bacterial enteritis,infectious diseases
EUR_008.52,893,57495,Intestinal infection due to C. difficile,infectious diseases
EUR_038,3172,50610,Septicemia,infectious diseases
EUR_038.3,1361,50610,Bacteremia,infectious diseases

In [26]:
assert emerge_traits_info.index.is_unique

# Trait associations

## PhenomeXcan

In [27]:
from traits import SHORT_TRAIT_NAMES

In [28]:
result_set = "phenomexcan"

In [29]:
def get_trait_objs(phenotype_full_code):
    if Trait.is_efo_label(phenotype_full_code):
        traits = Trait.get_traits_from_efo(phenotype_full_code)
    else:
        traits = [Trait.get_trait(code=phenotype_full_code)]

    # sort by sample size
    return sorted(traits, key=lambda x: x.n_cases / x.n, reverse=True)


def get_trait_description(phenotype_full_code):
    traits = get_trait_objs(phenotype_full_code)

    desc = traits[0].description
    if desc in SHORT_TRAIT_NAMES:
        return SHORT_TRAIT_NAMES[desc]

    return desc


def get_trait_n(phenotype_full_code):
    traits = get_trait_objs(phenotype_full_code)

    return traits[0].n


def get_trait_n_cases(phenotype_full_code):
    traits = get_trait_objs(phenotype_full_code)

    return traits[0].n_cases


def num_to_int_str(num):
    if pd.isnull(num):
        return ""

    return f"{num:,.0f}"


def get_part_clust(row):
    return f"{row.part_k} / {row.cluster_id}"

In [30]:
lv_assocs = phenomexcan_lv_trait_assocs[
    (phenomexcan_lv_trait_assocs["lv"] == LV_NAME)
    & (phenomexcan_lv_trait_assocs["fdr"] < 0.05)
].sort_values("fdr")

In [31]:
with pd.option_context(
    "display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None
):
    display(lv_assocs)

,phenotype,phenotype_desc,lv,pvalue,fdr
1367986,4101_raw,Heel broadband ultrasound attenuation (left),LV24,1.850282e-21,1.464922e-16
1064977,4120_raw,Heel broadband ultrasound attenuation (right),LV24,2.169228e-21,1.684413e-16
2039146,4124_raw,Heel bone mineral density (BMD) (right),LV24,4.254136e-12,4.580646e-08
463894,4123_raw,"Heel quantitative ultrasound index (QUI), direct entry (right)",LV24,5.295114e-12,5.557142e-08
3587749,4125_raw,"Heel bone mineral density (BMD) T-score, automated (right)",LV24,5.298654e-12,5.557142e-08
4018083,MAGNETIC_CH2.DB.ratio,CH2DB NMR,LV24,8.883343e-11,7.441766e-07
790591,4105_raw,Heel bone mineral density (BMD) (left),LV24,9.692989e-11,8.036656e-07
118444,4104_raw,"Heel quantitative ultrasound index (QUI), direct entry (left)",LV24,1.357855e-10,1.082856e-06
2049016,4106_raw,"Heel bone mineral density (BMD) T-score, automated (left)",LV24,1.359666e-10,1.082856e-06
1587100,3148_raw,Heel bone mineral density (BMD),LV24,1.296695e-09,8.245383e-06
678075,2463,Fractured/broken bones in last 5 years,LV24,1.430898e-09,8.999539e-06
918902,78_raw,"Heel bone mineral density (BMD) T-score, automated",LV24,1.743966e-09,1.075086e-05
3941096,3147_raw,"Heel quantitative ultrasound index (QUI), direct entry",LV24,1.742800e-09,1.075086e-05
1621646,3144_raw,"Heel Broadband ultrasound attenuation, direct entry",LV24,4.776883e-09,2.634997e-05
3556166,S52,Diagnoses - main ICD10: S52 Fracture of forearm,LV24,6.229938e-07,1.754208e-03
2494153,6151_5,Fractured bone site(s): Wrist,LV24,7.690623e-07,2.082718e-03
4033875,GEFOS_Forearm,Bone Mineral Density,LV24,1.300576e-06,3.204080e-03
936663,20003_1140882910,Treatment/medication code: daktacort cream (20003_1140882910),LV24,3.102543e-06,6.391582e-03

In [32]:
lv_assocs = lv_assocs.assign(
    phenotype_desc=lv_assocs["phenotype"].apply(get_trait_description)
)

In [33]:
lv_assocs = lv_assocs.assign(n=lv_assocs["phenotype"].apply(get_trait_n))

In [34]:
lv_assocs = lv_assocs.assign(n_cases=lv_assocs["phenotype"].apply(get_trait_n_cases))

In [35]:
# lv_assocs = lv_assocs.assign(coef=lv_assocs["coef"].apply(lambda x: f"{x:.3f}"))

In [36]:
lv_assocs = lv_assocs.assign(
    fdr=lv_assocs["fdr"].apply(lambda x: f"{x:.2e}".replace("-", "&#8209;"))
)

In [37]:
lv_assocs = lv_assocs.assign(n=lv_assocs["n"].apply(num_to_int_str))

In [38]:
lv_assocs = lv_assocs.assign(n_cases=lv_assocs["n_cases"].apply(num_to_int_str))

In [39]:
# lv_assocs = lv_assocs.assign(part_clust="")  # lv_assocs.apply(get_part_clust, axis=1))

In [40]:
lv_assocs = lv_assocs.drop(columns=["phenotype"])

In [41]:
lv_assocs.shape

(18, 6)

In [42]:
lv_assocs = lv_assocs[["phenotype_desc", "n", "n_cases", "fdr"]]

In [43]:
lv_assocs = lv_assocs.rename(
    columns={
        "part_clust": "Partition / cluster",
        "lv": "Latent variable (LV)",
        #         "coef": r"$\beta$",
        "fdr": "FDR",
        "phenotype_desc": "Trait description",
        "n": "Sample size",
        "n_cases": "Cases",
    }
)

In [44]:
with pd.option_context(
    "display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None
):
    display(lv_assocs)

,Trait description,Sample size,Cases,FDR
1367986,Heel broadband ultrasound attenuation (left),"114,625",,1.46e&#8209;16
1064977,Heel broadband ultrasound attenuation (right),"114,609",,1.68e&#8209;16
2039146,Heel bone mineral density (BMD) (right),"114,552",,4.58e&#8209;08
463894,"Heel quantitative ultrasound index, direct entry (right)","114,614",,5.56e&#8209;08
3587749,"Heel bone mineral density T-score, automated (right)","114,614",,5.56e&#8209;08
4018083,CH2DB NMR,"24,154",,7.44e&#8209;07
790591,Heel bone mineral density (BMD) (left),"114,561",,8.04e&#8209;07
118444,"Heel quantitative ultrasound index (QUI), direct entry (left)","114,630",,1.08e&#8209;06
2049016,"Heel bone mineral density (BMD) T-score, automated (left)","114,630",,1.08e&#8209;06
1587100,Heel bone mineral density (BMD),"206,496",,8.25e&#8209;06
678075,Fractured/broken bones in last 5 years,"359,241","34,780",9.00e&#8209;06
918902,"Heel bone mineral density (BMD) T-score, automated","206,589",,1.08e&#8209;05
3941096,"Heel quantitative ultrasound index (QUI), direct entry","206,589",,1.08e&#8209;05
1621646,"Heel Broadband ultrasound attenuation, direct entry","206,576",,2.63e&#8209;05
3556166,Diagnoses - main ICD10: S52 Fracture of forearm,"361,194","5,080",1.75e&#8209;03
2494153,Fractured bone site(s): Wrist,"359,241","7,200",2.08e&#8209;03
4033875,Bone Mineral Density,"49,988",,3.20e&#8209;03
936663,Treatment/medication code: daktacort cream,"361,141",246,6.39e&#8209;03

## eMERGE

In [ ]:
epval = 0.005

In [46]:
result_set = "emerge"

In [47]:
lv_assocs = emerge_lv_trait_assocs[
    (emerge_lv_trait_assocs["lv"] == LV_NAME) & (emerge_lv_trait_assocs["fdr"] < 0.05)
].sort_values("fdr")

In [48]:
with pd.option_context(
    "display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None
):
    display(lv_assocs)

Empty DataFrame
Columns: [phenotype, phenotype_desc, lv, pvalue, fdr]
Index: []

In [49]:
lv_assocs = lv_assocs.assign(
    phenotype_desc=lv_assocs["phenotype"].apply(
        lambda x: emerge_traits_info.loc[x, "phenotype"]
    )
)

In [50]:
lv_assocs = lv_assocs.assign(
    n=lv_assocs["phenotype"].apply(
        lambda x: emerge_traits_info.loc[x, ["eur_n_cases", "eur_n_controls"]].sum()
    )
)

In [51]:
lv_assocs = lv_assocs.assign(
    n_cases=lv_assocs["phenotype"].apply(
        lambda x: emerge_traits_info.loc[x, "eur_n_cases"]
    )
)

In [52]:
lv_assocs["phenotype"] = lv_assocs["phenotype"].apply(lambda x: x.split("EUR_")[1])

In [53]:
# lv_assocs = lv_assocs.assign(coef=lv_assocs["coef"].apply(lambda x: f"{x:.3f}"))

In [54]:
lv_assocs = lv_assocs.assign(
    fdr=lv_assocs["fdr"].apply(lambda x: f"{x:.2e}".replace("-", "&#8209;"))
)

In [55]:
lv_assocs = lv_assocs.assign(n=lv_assocs["n"].apply(num_to_int_str))

In [56]:
lv_assocs = lv_assocs.assign(n_cases=lv_assocs["n_cases"].apply(num_to_int_str))

In [57]:
lv_assocs = lv_assocs.rename(columns={"phenotype": "phecode"})

In [58]:
lv_assocs.shape

(0, 7)

In [59]:
lv_assocs = lv_assocs[["phecode", "phenotype_desc", "n", "n_cases", "fdr"]]

In [60]:
lv_assocs = lv_assocs.rename(
    columns={
        "lv": "Latent variable (LV)",
        #         "coef": r"$\beta$",
        "fdr": "FDR",
        "phecode": "Phecode",
        "phenotype_desc": "Trait description",
        "n": "Sample size",
        "n_cases": "Cases",
    }
)

In [61]:
with pd.option_context(
    "display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None
):
    display(lv_assocs)

Empty DataFrame
Columns: [Phecode, Trait description, Sample size, Cases, FDR]
Index: []